//! Bitboard attack generation and precomputed ray lookups.
//!
//! - Leapers (Pawn, Knight, King): Precomputed at compile-time via `const fn`.
//! - Sliders (Bishop, Rook, Queen): Lookups into an `ATTACK_TABLE` generated by `build.rs`.
//!   Uses hardware `PEXT` on BMI2 targets and standard magic multiplication on fallback targets.

use crate::core::defs::{Bitboard, Color, FILE_A, FILE_H, FILE_MASKS, NOT_AB, NOT_GH, RANK_MASKS, Square};

/// Pawn capture targets, indexed by `[Color][Square]`.
pub static PAWN_ATTACKS: [[Bitboard; 64]; 2] = init_pawn_attacks();

/// Passed pawn candidate masks, indexed by `[Color][Square]`.
/// Spans the pawn's file and adjacent files ahead of its rank toward promotion.
pub static PASSED_PAWN_MASKS: [[Bitboard; 64]; 2] = init_passed_pawn_masks();

/// Knight jump targets, indexed by `[Square]`. Occupancy-independent.
pub static KNIGHT_ATTACKS: [Bitboard; 64] = init_knight_attacks();

/// King step targets, indexed by `[Square]`. Occupancy-independent.
pub static KING_ATTACKS: [Bitboard; 64] = init_king_attacks();

/// Unobstructed rook rays (full rank ∪ file, excluding source square).
pub static PSEUDO_ROOK_ATTACKS: [Bitboard; 64] = init_pseudo_rook_attacks();

/// Unobstructed bishop rays (all 4 diagonals, excluding source square).
pub static PSEUDO_BISHOP_ATTACKS: [Bitboard; 64] = init_pseudo_bishop_attacks();

// Build-time generated tables: ROOKS, BISHOPS, ATTACK_TABLE, LINES, BETWEEN.
include!(concat!(env!("OUT_DIR"), "/magics.rs"));

/// Per-square lookup parameters for slider attacks.
///
/// On BMI2 targets, `_pext_u64` extracts occupancy bits directly into a dense offset.
/// On fallback targets, magic multiplication and shifting hash the occupancy into an index.
#[cfg(use_pext)]
#[derive(Clone, Copy, Debug)]
pub struct MagicEntry {
    pub mask: u64,
    pub offset: u32,
}

#[cfg(not(use_pext))]
#[derive(Clone, Copy, Debug)]
pub struct MagicEntry {
    pub mask: u64,
    pub magic: u64,
    pub shift: u8,
    pub offset: u32,
}

/// Resolves the flat index into `ATTACK_TABLE` for a slider at `sq` with occupancy `occ`.
macro_rules! magic_index {
    ($entries:expr, $sq:expr, $occ:expr) => {{
        let entry = debug_index!($entries, $sq);

        #[cfg(use_pext)]
        // SAFETY: a pure arithmetic intrinsic, and the target_feature gate is what
        // guarantees the hardware has it.
        let key = unsafe { core::arch::x86_64::_pext_u64($occ, entry.mask) } as usize;

        #[cfg(not(use_pext))]
        let key = (($occ & entry.mask).wrapping_mul(entry.magic) >> entry.shift) as usize;
        key + entry.offset as usize
    }};
}

/// A pawn's two capture squares.
#[inline(always)]
pub fn atk_pawn(sq: Square, color: Color) -> Bitboard { PAWN_ATTACKS[color][sq] }

/// The span a pawn must have clear of enemy pawns to count as passed.
#[inline(always)]
pub fn passed_span(sq: Square, color: Color) -> Bitboard { PASSED_PAWN_MASKS[color][sq] }

/// A knight's eight destinations.
#[inline(always)]
pub fn atk_knight(square: Square) -> Bitboard { KNIGHT_ATTACKS[square] }

/// Diagonal attacks, stopped by `occupancy`.
#[inline(always)]
pub fn atk_bishop(square: Square, occupancy: Bitboard) -> Bitboard {
    let idx = magic_index!(BISHOPS, usize::from(square), occupancy.0);
    Bitboard(ATTACK_TABLE[idx])
}

/// Rank and file attacks, stopped by `occupancy`.
#[inline(always)]
pub fn atk_rook(square: Square, occupancy: Bitboard) -> Bitboard {
    let idx = magic_index!(ROOKS, usize::from(square), occupancy.0);
    Bitboard(ATTACK_TABLE[idx])
}

/// A king's eight neighbours.
#[inline(always)]
pub fn atk_king(square: Square) -> Bitboard { KING_ATTACKS[square] }

/// The whole line through both squares, rank, file or diagonal.
/// Empty when they do not share one.
#[inline(always)]
pub fn line_bb(sq1: Square, sq2: Square) -> Bitboard { Bitboard(LINES[sq1][sq2]) }

/// The squares strictly between the two, endpoints excluded.
/// Empty when they do not share a line.
#[inline(always)]
pub fn between_bb(sq1: Square, sq2: Square) -> Bitboard { Bitboard(BETWEEN[sq1][sq2]) }

/// ```text
/// White pawn on d4 (targets c5, e5):    Black pawn on d5 (targets c4, e4):
///   . . c . e . . .                       . . . . . . . .
///   . . . P . . . .                       . . . p . . . .
///   . . . . . . . .                       . . c . e . . .
/// ```
const fn init_pawn_attacks() -> [[Bitboard; 64]; 2] {
    let mut table = [[Bitboard(0); 64]; 2];
    let mut sq = 0usize;
    while sq < 64 {
        let bb = 1u64 << sq;
        // White captures northeast (+9) and northwest (+7)
        table[0][sq] = Bitboard(((bb << 9) & !FILE_A.0) | ((bb << 7) & !FILE_H.0));
        // Black captures southeast (-9) and southwest (-7)
        table[1][sq] = Bitboard(((bb >> 9) & !FILE_H.0) | ((bb >> 7) & !FILE_A.0));
        sq += 1;
    }
    table
}

/// Table index 0 = White (ranks above), index 1 = Black (ranks below).
const fn init_passed_pawn_masks() -> [[Bitboard; 64]; 2] {
    let mut table = [[Bitboard(0); 64]; 2];
    let mut sq = 0usize;
    while sq < 64 {
        let file = sq % 8;
        let rank = sq / 8;

        // Front span includes current file and immediate flanking files.
        let mut files = FILE_MASKS[file].0;
        if file > 0 {
            files |= FILE_MASKS[file - 1].0;
        }
        if file < 7 {
            files |= FILE_MASKS[file + 1].0;
        }

        // Mask ranks strictly ahead:
        // Rank 7 for White shifts by 64 bits (`unbounded_shl` returns 0 without panicking).
        let above = (!0u64).unbounded_shl(8 * (rank as u32 + 1));
        let below = (1u64 << (8 * rank)) - 1;

        table[0][sq] = Bitboard(files & above);
        table[1][sq] = Bitboard(files & below);
        sq += 1;
    }
    table
}

/// ```text
///   . x . x .
///   x . . . x
///   . . N . .
///   x . . . x
///   . x . x .
/// ```
const fn init_knight_attacks() -> [Bitboard; 64] {
    let mut table = [Bitboard(0); 64];
    let mut sq = 0usize;
    while sq < 64 {
        let bb = 1u64 << sq;

        table[sq] = Bitboard(
            ((bb << 17) & !FILE_A.0)  //  ↑↑→
          | ((bb << 15) & !FILE_H.0)  //  ↑↑←
          | ((bb << 10) &  NOT_AB.0)  //  ↑→→
          | ((bb <<  6) &  NOT_GH.0)  //  ↑←←
          | ((bb >>  6) &  NOT_AB.0)  //  ↓→→
          | ((bb >> 10) &  NOT_GH.0)  //  ↓←←
          | ((bb >> 15) & !FILE_A.0)  //  ↓↓→
          | ((bb >> 17) & !FILE_H.0), //  ↓↓←
        );
        sq += 1;
    }
    table
}

/// Precomputes 1-step king moves across all 8 compass directions.
const fn init_king_attacks() -> [Bitboard; 64] {
    let mut table = [Bitboard(0); 64];
    let mut sq = 0usize;
    while sq < 64 {
        let bb = 1u64 << sq;

        table[sq] = Bitboard(
            (bb << 8)                // N
          | (bb >> 8)                // S
          | ((bb << 1) & !FILE_A.0)  // E
          | ((bb >> 1) & !FILE_H.0)  // W
          | ((bb << 9) & !FILE_A.0)  // NE
          | ((bb << 7) & !FILE_H.0)  // NW
          | ((bb >> 7) & !FILE_A.0)  // SE
          | ((bb >> 9) & !FILE_H.0), // SW
        );
        sq += 1;
    }
    table
}

const fn init_pseudo_rook_attacks() -> [Bitboard; 64] {
    let mut table = [Bitboard(0); 64];
    let mut sq = 0usize;
    while sq < 64 {
        let rank = sq / 8;
        let file = sq % 8;
        let rank_mask = RANK_MASKS[rank];
        let file_mask = FILE_MASKS[file];
        let sq_bit = 1u64 << sq;

        table[sq] = (rank_mask | file_mask) & !sq_bit;
        sq += 1;
    }
    table
}

const fn init_pseudo_bishop_attacks() -> [Bitboard; 64] {
    let mut table = [Bitboard(0); 64];
    let mut sq = 0usize;
    while sq < 64 {
        let rank = (sq / 8) as i8;
        let file = (sq % 8) as i8;

        table[sq] = Bitboard(
            diag_ray(rank, file, 1, 1)   // NE
          | diag_ray(rank, file, 1, -1)  // NW
          | diag_ray(rank, file, -1, 1)  // SE
          | diag_ray(rank, file, -1, -1), // SW
        );
        sq += 1;
    }
    table
}

/// Casts a single diagonal ray from `(rank, file)` with step `(dr, df)` to the board edge.
const fn diag_ray(rank: i8, file: i8, dr: i8, df: i8) -> u64 {
    let (mut r, mut f) = (rank + dr, file + df);
    let mut ray = 0u64;
    while r >= 0 && r < 8 && f >= 0 && f < 8 {
        ray |= 1u64 << (r * 8 + f);
        r += dr;
        f += df;
    }
    ray
}
