[package]
name = "tuner"
version = "0.2.8"
edition = "2024"
rust-version = "1.97.1"

[lib]
path = "src/lib.rs"

[[bin]]
name = "evaltune"
path = "src/bin/evaltune.rs"

[[bin]]
name = "searchtune"
path = "src/bin/searchtune.rs"

[dependencies]
soul = { path = "../" }
clap = { version = "4.6.1", default-features = false, features = ["std", "derive", "help", "usage", "error-context", "suggestions"] }
fastrand = "2.4.1"
parking_lot = "0.12.5"
rayon = "1.12.0"
zerocopy = { version = "0.8.52", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
zstd = { version = "0.13.3", default-features = false }
toml = "1.1.2"
paste = "1.0.15"
thiserror = "2.0.18"
ctrlc = "3.5.2"

[features]
default = []
searchtune = ["soul/searchtune"]
